# Generated by Django 4.2.16 on 2024-10-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='password',
            field=models.CharField(default='ganga', max_length=90),
        ),
        migrations.AddField(
            model_name='trainer',
            name='username',
            field=models.CharField(default='user', max_length=80),
        ),
    ]
