# Generated by Django 4.2.16 on 2024-10-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_trainer_password_remove_trainer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
