# Generated by Django 4.2.16 on 2024-10-04 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_trainer_password_remove_trainer_username'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.trainer'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('trainer', 'course')},
        ),
    ]
