# Generated by Django 4.2.16 on 2024-10-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
